# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scann/proto/restricts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scann/proto/restricts.proto',
  package='research_scann',
  syntax='proto2',
  serialized_options=_b('\370\001\001'),
  serialized_pb=_b('\n\x1bscann/proto/restricts.proto\x12\x0eresearch_scann\"@\n\nV3Restrict\x12\x32\n\nnamespaces\x18\x01 \x03(\x0b\x32\x1e.research_scann.TokenNamespace\"\x9b\x01\n\x0eTokenNamespace\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x15\n\rstring_tokens\x18\x03 \x03(\t\x12\x19\n\ruint64_tokens\x18\x02 \x03(\x06\x42\x02\x10\x01\x12\x1f\n\x17string_blacklist_tokens\x18\x05 \x03(\t\x12#\n\x17uint64_blacklist_tokens\x18\x04 \x03(\x06\x42\x02\x10\x01\"\x82\x01\n\x0fRestrictsConfig\x12\x16\n\x07\x65nabled\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x1e\n\x13restrict_cache_size\x18\x02 \x01(\x05:\x01\x30\x12\x37\n\x0cv3_restricts\x18\x03 \x01(\x0b\x32!.research_scann.V3RestrictsConfig\"\x81\x02\n\x11V3RestrictsConfig\x12p\n\x1d\x65mpty_namespace_matching_mode\x18\x01 \x01(\x0e\x32<.research_scann.V3RestrictsConfig.EmptyNamespaceMatchingMode:\x0bUNSPECIFIED\"z\n\x1a\x45mptyNamespaceMatchingMode\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x10\n\x0c\x46ORWARD_MODE\x10\x01\x12\x10\n\x0cREVERSE_MODE\x10\x02\x12\x11\n\rLAX_SYMMETRIC\x10\x03\x12\x14\n\x10STRICT_SYMMETRIC\x10\x04\x42\x03\xf8\x01\x01')
)



_V3RESTRICTSCONFIG_EMPTYNAMESPACEMATCHINGMODE = _descriptor.EnumDescriptor(
  name='EmptyNamespaceMatchingMode',
  full_name='research_scann.V3RestrictsConfig.EmptyNamespaceMatchingMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORWARD_MODE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REVERSE_MODE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAX_SYMMETRIC', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRICT_SYMMETRIC', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=540,
  serialized_end=662,
)
_sym_db.RegisterEnumDescriptor(_V3RESTRICTSCONFIG_EMPTYNAMESPACEMATCHINGMODE)


_V3RESTRICT = _descriptor.Descriptor(
  name='V3Restrict',
  full_name='research_scann.V3Restrict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespaces', full_name='research_scann.V3Restrict.namespaces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=111,
)


_TOKENNAMESPACE = _descriptor.Descriptor(
  name='TokenNamespace',
  full_name='research_scann.TokenNamespace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='research_scann.TokenNamespace.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_tokens', full_name='research_scann.TokenNamespace.string_tokens', index=1,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uint64_tokens', full_name='research_scann.TokenNamespace.uint64_tokens', index=2,
      number=2, type=6, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_blacklist_tokens', full_name='research_scann.TokenNamespace.string_blacklist_tokens', index=3,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uint64_blacklist_tokens', full_name='research_scann.TokenNamespace.uint64_blacklist_tokens', index=4,
      number=4, type=6, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=269,
)


_RESTRICTSCONFIG = _descriptor.Descriptor(
  name='RestrictsConfig',
  full_name='research_scann.RestrictsConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='research_scann.RestrictsConfig.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restrict_cache_size', full_name='research_scann.RestrictsConfig.restrict_cache_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v3_restricts', full_name='research_scann.RestrictsConfig.v3_restricts', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=402,
)


_V3RESTRICTSCONFIG = _descriptor.Descriptor(
  name='V3RestrictsConfig',
  full_name='research_scann.V3RestrictsConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='empty_namespace_matching_mode', full_name='research_scann.V3RestrictsConfig.empty_namespace_matching_mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _V3RESTRICTSCONFIG_EMPTYNAMESPACEMATCHINGMODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=662,
)

_V3RESTRICT.fields_by_name['namespaces'].message_type = _TOKENNAMESPACE
_RESTRICTSCONFIG.fields_by_name['v3_restricts'].message_type = _V3RESTRICTSCONFIG
_V3RESTRICTSCONFIG.fields_by_name['empty_namespace_matching_mode'].enum_type = _V3RESTRICTSCONFIG_EMPTYNAMESPACEMATCHINGMODE
_V3RESTRICTSCONFIG_EMPTYNAMESPACEMATCHINGMODE.containing_type = _V3RESTRICTSCONFIG
DESCRIPTOR.message_types_by_name['V3Restrict'] = _V3RESTRICT
DESCRIPTOR.message_types_by_name['TokenNamespace'] = _TOKENNAMESPACE
DESCRIPTOR.message_types_by_name['RestrictsConfig'] = _RESTRICTSCONFIG
DESCRIPTOR.message_types_by_name['V3RestrictsConfig'] = _V3RESTRICTSCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

V3Restrict = _reflection.GeneratedProtocolMessageType('V3Restrict', (_message.Message,), {
  'DESCRIPTOR' : _V3RESTRICT,
  '__module__' : 'scann.proto.restricts_pb2'
  # @@protoc_insertion_point(class_scope:research_scann.V3Restrict)
  })
_sym_db.RegisterMessage(V3Restrict)

TokenNamespace = _reflection.GeneratedProtocolMessageType('TokenNamespace', (_message.Message,), {
  'DESCRIPTOR' : _TOKENNAMESPACE,
  '__module__' : 'scann.proto.restricts_pb2'
  # @@protoc_insertion_point(class_scope:research_scann.TokenNamespace)
  })
_sym_db.RegisterMessage(TokenNamespace)

RestrictsConfig = _reflection.GeneratedProtocolMessageType('RestrictsConfig', (_message.Message,), {
  'DESCRIPTOR' : _RESTRICTSCONFIG,
  '__module__' : 'scann.proto.restricts_pb2'
  # @@protoc_insertion_point(class_scope:research_scann.RestrictsConfig)
  })
_sym_db.RegisterMessage(RestrictsConfig)

V3RestrictsConfig = _reflection.GeneratedProtocolMessageType('V3RestrictsConfig', (_message.Message,), {
  'DESCRIPTOR' : _V3RESTRICTSCONFIG,
  '__module__' : 'scann.proto.restricts_pb2'
  # @@protoc_insertion_point(class_scope:research_scann.V3RestrictsConfig)
  })
_sym_db.RegisterMessage(V3RestrictsConfig)


DESCRIPTOR._options = None
_TOKENNAMESPACE.fields_by_name['uint64_tokens']._options = None
_TOKENNAMESPACE.fields_by_name['uint64_blacklist_tokens']._options = None
# @@protoc_insertion_point(module_scope)
